server:
  port: 8081
spring:
  datasource:
    username: "root"
    password: "Root_1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://rm-uf6n6u176m4zxbd75xo.mysql.rds.aliyuncs.com:3306/test_hub?useUnicode=true&characterEncoding=utf8"
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    cluster:
      nodes: 172.25.218.162:7001,172.25.218.162:7002,172.25.218.162:7003,172.25.218.162:7004,172.25.218.162:7005 #集群节点
      lettuce:
        pool:
          max-active: 10  #连接池最大连接数
          max-idle: 8     #连接池中最大空闲连接数
          max-wait: -1ms  #连接池最大等待阻塞时间
          min-idle: 0     #连接池中最小空闲数
      timeout: 5000

security:
  key:
    seed: liuyuchen

user:
  login:
    type: "redisLoginService"
#    type: "sessionLoginService"